runtime: nodejs20
service: frontend
instance_class: F2 # instance class affects cost and performance
env_variables:
  NODE_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 4

handlers:
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301
    login: required

# Handle static assets like JS, CSS, images, etc.
  - url: /assets/
    static_dir: dist/assets

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301